_BASE_: "../_base_/things_baseline.yaml"
TARGET_SCALE_FACTOR: 20.0
DATA:
  BATCH_SIZE: 2 # Effective Batch Size = 2 x 2 GPUs = 4
  NORM_PARAMS: {"use": True, "mean":[0.0, 0.0, 0.0], "std":[255.0, 255.0, 255.0]}
SCHEDULER:
  USE: True
  NAME: OneCycleLR
  PARAMS:
    max_lr: 0.000125
    total_steps: 380100
    pct_start: 0.05
    cycle_momentum: False
    anneal_strategy: linear
CRITERION:
  CUSTOM: True
  NAME: MultiScaleLoss
  PARAMS:
    norm: "l2" 
    weights: [0.32, 0.08, 0.02, 0.01, 0.005]
    average: "sum"
    resize_flow: "downsample"
    use_valid_range: True
    valid_range: [[1000,1000],[1000,1000],[1000,1000],[1000,1000],[1000,1000]]
DEVICE: "all"
DISTRIBUTED:
  USE: True
  WORLD_SIZE: 2
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
  SYNC_BATCH_NORM: True
EPOCHS: null
NUM_STEPS: 380100
LOG_DIR: "./logs"
CKPT_DIR: "./ckpts"
LOG_ITERATIONS_INTERVAL: 100
CKPT_INTERVAL: 100000
VALIDATE_INTERVAL: 10000
VALIDATE_ON: metric