codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, tree"
  behavior: default
  require_changes: no

ignore:
  - "ezflow/data"
  - "ezflow/config"
  - "ezflow/model_zoo" 