repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
        - id: seed-isort-config
          args: [--exclude=^((examples|docs)/.*)$]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
        - id: isort

  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
        - id: black
          language_version: python3

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false


  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.8.3
  #   hooks:
  #       - id: flake8