name: ezflow
channels:
  - fvcore
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=21.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cffi=1.14.6
  - click=8.0.1
  - colorama=0.4.4
  - cudatoolkit=11.3
  - cycler=0.10.0
  - dnspython=1.16.0
  - docopt=0.6.2
  - einops=0.3.2
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - icu=58.2
  - intel-openmp=2021.2.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libffi=3.3
  - libiconv=1.15  
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - mypy_extensions=0.4.3
  - networkx=2.6.2
  - ninja=1.10.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1l
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.2.4
  - pthread-stubs=0.4
  - pycparser=2.20
  - pymongo=3.11.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python_abi=3.7
  - pytorch=1.10.1
  - qt=5.9.7
  - regex=2021.7.6
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - toml=0.10.2
  - torchvision=0.11.2
  - tornado=6.1
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.0
  - ujson=1.35
  - whichcraft=0.6.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.13.0
    - alabaster==0.7.12
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - argh==0.26.2
    - arrow==0.13.1
    - babel==2.9.1
    - backports-entry-points-selectable==1.1.0
    - binaryornot==0.4.4
    - black==21.7b0
    - bleach==3.3.0
    - bump2version==0.5.11
    - cachetools==4.2.2
    - certifi==2021.5.30
    - cfgv==3.3.0
    - chardet==4.0.0
    - charset-normalizer==2.0.1
    - cookiecutter==1.7.3
    - coverage==5.5
    - cryptography==3.4.8
    - distlib==0.3.2
    - docutils==0.17.1
    - easydict==1.9
    - entrypoints==0.3
    - filelock==3.0.12
    - flake8==3.9.2
    - fvcore==0.1.5.post20210722
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.5
    - grpcio==1.40.0
    - identify==2.2.13
    - idna==3.2
    - imagesize==1.2.0
    - importlib-metadata==0.23
    - iniconfig==1.1.1
    - iopath==0.1.9
    - jinja2==3.0.1
    - jinja2-time==0.2.0
    - markdown==3.3.4
    - markupsafe==2.0.1
    - mccabe==0.6.1
    - nodeenv==1.6.0
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.3.56
    - packaging==21.0
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pip==21.2.4
    - pkginfo==1.7.1
    - platformdirs==2.0.0
    - pluggy==0.13.1
    - portalocker==2.3.0
    - poyo==0.5.0
    - pre-commit==2.14.0
    - protobuf==3.17.3
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.7.0
    - pyflakes==2.3.1
    - pygments==2.9.0
    - pytest==6.2.4
    - python-slugify==5.0.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - readme-renderer==29.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rsa==4.7.2
    - scipy==1.7.0
    - snowballstemmer==2.1.0
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - tomli==1.2.1
    - torchmetrics==0.5.0
    - tox==3.14.0
    - tqdm==4.61.2
    - twine==1.14.0
    - unidecode==1.3.2
    - urllib3==1.26.6
    - virtualenv==20.5.0
    - watchdog==0.9.0
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - wheel==0.37.0
    - yacs==0.1.8