NAME: DCVNet
ENCODER: 
  NAME: DCVNetBackbone
  IN_CHANNELS: 3
  OUT_CHANNELS: 256
  NORM: instance
  P_DROPOUT: 0.0
  LAYER_CONFIG: [64, 96, 128]
  NUM_RESIDUAL_LAYERS: [1, 2, 2]
  INTERMEDIATE_FEATURES: True
DECODER:
  NAME: DCVDilatedFlowStackFilter