NAME: DICL
ENCODER:
  NAME: GANetBackbone
  IN_CHANNELS: 3
  OUT_CHANNELS: 32
SIMILARITY:
  NAME: LearnableMatchingCost
  MAX_U: 3
  MAX_V: 3
  CONFIG: [64, 96, 128, 64, 32, 1]
  REMOVE_WARP_HOLE: True
  CUDA_COST_COMPUTE: False
  MATCHING_NET:
    NAME: Conv2DMatching
    CONFIG: [64, 96, 128, 64, 32, 1]
DECODER:
  NAME: SoftArg2DFlowRegression
  MAX_U: 3
  MAX_V: 3
  OPERATION: argmax
SEARCH_RANGE: [3, 3, 3, 3, 3]
CONTEXT_NET: True
SUP_RAW_FLOW: False
SCALE_FACTORS: [0.25, 0.125, 0.0625, 0.03125, 0.015625]
SCALE_CONTEXTS: [1.0, 1.0, 1.0, 1.0, 1.0]
DAP:
  USE_DAP: True
  INIT_ID: True
  MAX_DISPLACEMENT: 3
  TEMPERATURE: False
  TEMP_FACTOR: 1.e-6

