NAME: FlowNetS
ENCODER:
  NAME: ConvEncoder
  IN_CHANNELS: 6
  OUT_CHANNELS: [64, 128, 256, 256, 512, 512, 512, 512, 1024, 1024]
  BATCH_NORM: True
DECODER:
  NAME: ConvFlowDecoder
  IN_CHANNELS: 1024
  OUT_CHANNELS: [512, 256, 128, 64]
INTERPOLATE_FLOW: True
