NAME: PWCNet
ENCODER:
  NAME: PyramidEncoder
  IN_CHANNELS: 3
  CONFIG: [16, 32, 64, 96, 128, 196]
SIMILARITY:
  NAME: CorrelationLayer
  PAD_SIZE: 4
  MAX_DISPLACEMENT: 4
DECODER:
  NAME: ConvDecoder
  CONFIG: [128, 128, 96, 64, 32]
  TO_FLOW: True
INTERPOLATE_FLOW: True
FLOW_SCALE_FACTOR: 20.0