NAME: PWCNet
ENCODER:
  NAME: PyramidEncoder
  IN_CHANNELS: 3
  CONFIG: [16, 32, 64, 96, 128, 196]
DECODER:
  NAME: PyramidDecoder
  CONFIG: [128, 128, 96, 64, 32]
  TO_FLOW: True
  SIMILARITY:
    PAD_SIZE: 0
    MAX_DISPLACEMENT: 4
  FLOW_SCALE_FACTOR: 20.0