NAME: RAFT
ENCODER:
  FEATURE: 
    NAME: RAFTBackboneSmall
    IN_CHANNELS: 3
    OUT_CHANNELS: 128
    NORM: instance
    P_DROPOUT: 0.0
    LAYER_CONFIG: [32, 64, 96]
  CONTEXT:
    NAME: RAFTBackboneSmall
    IN_CHANNELS: 3
    OUT_CHANNELS: 160
    NORM: batch
    P_DROPOUT: 0.0
    LAYER_CONFIG: [32, 64, 96]
HIDDEN_DIM: 96
CONTEXT_DIM: 64
SIMILARITY:
  NAME: MutliScalePairwise4DCorr
  NUM_LEVELS: 4
DECODER:
  NAME: RecurrentLookupUpdateBlock
  INPUT_DIM: 96
CORR_RADIUS: 4
CORR_LEVELS: 3
MIXED_PRECISION: False
UPDATE_ITERS: 12