DATA:
  TRAIN_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: "../../../Datasets/FlyingChairs_release/data"
  VAL_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: "../../../Datasets/FlyingChairs_release/data"
  BATCH_SIZE: 16
  NUM_WORKERS: 1
  PIN_MEMORY: True
  TRAIN_CROP_SIZE: [256, 256]
  VAL_CROP_SIZE: [256, 256]
  AUGMENTATION:
    USE: True
    PARAMS:
      CROP_SIZE: [256, 256]
      TRAINING:
        SPATIAL_AUG_PARAMS: {"min_scale": -0.1, "max_scale": 1.0, "flip": True}
      VALIDATION:
        SPATIAL_AUG_PARAMS: {"aug_prob": 0.0}
        COLOR_AUG_PARAMS: {"aug_prob": 0.0}
        ERASER_AUG_PARAMS: {"aug_prob": 0.0}
OPTIMIZER:
  NAME: AdamW
  LR: 0.0004
  PARAMS:
    weight_decay: 0.0001
    eps: 1.e-08
SCHEDULER:
  USE: True
  NAME: OneCycleLR
  PARAMS:
    max_lr: 0.0004
    epochs: 100
    steps_per_epoch: 2300
    pct_start: 0.05
    cycle_momentum: False
    anneal_strategy: linear
CRITERION:
  CUSTOM: True
  NAME: MultiScaleLoss
  PARAMS: 
    weights: [1, 0.5, 0.25, 0.125, 0.0625]
GRAD_CLIP: 
  USE: True
  VALUE: 1.0
TARGET_SCALE_FACTOR: 1
APPEND_VALID_MASK: False
MIXED_PRECISION: False
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 2
  RANK: 0
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
LOG_DIR: "./logs"
LOG_ITERATIONS_INTERVAL: 100
CKPT_DIR: "./ckpts"
CKPT_INTERVAL: 1
VALIDATE_INTERVAL: 1
VALIDATE_ON: metric
EPOCHS: 100
NUM_STEPS: null
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: 100
  START_EPOCH: null