DATA:
  TRAIN_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: ""
  VAL_DATASET:
    NAME: "flyingchairs"
    ROOT_DIR: "" 
  BATCH_SIZE: 10
  NUM_WORKERS: 1
  PIN_MEMORY: True
  APPEND_VALID_MASK: True
  TARGET_SCALE_FACTOR: 1
  TRAIN_CROP_SIZE: [256, 256]
  VAL_CROP_SIZE: [256, 256]
  AUGMENTATION:
    USE: True
    PARAMS:
      TRAINING:
        SPATIAL_AUG_PARAMS: {"min_scale": -0.1, "max_scale": 1.0, "flip": True}
      VALIDATION:
        SPATIAL_AUG_PARAMS: {"aug_prob": 0.0}
        COLOR_AUG_PARAMS: {"aug_prob": 0.0}
        ERASER_AUG_PARAMS: {"aug_prob": 0.0}
OPTIMIZER:
  NAME: Adam
  LR: 0.0003
  PARAMS: #null
    betas: [0.9, 0.999]
    eps: 1.e-08
SCHEDULER:
  USE: True
  NAME: StepLR
  PARAMS:
    step_size: 10
    gamma: 0.1
CRITERION:
  CUSTOM: True
  NAME: L1Loss
  PARAMS: null
GRAD_CLIP: 
  USE: True
  VALUE: 1.0
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 2
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
  SYNC_BATCH_NORM: True
LOG_DIR: "./logs"
LOG_ITERATIONS_INTERVAL: 1000
VALIDATE_INTERVAL: 2
VALIDATE_ON: loss
CKPT_DIR: "./ckpts"
CKPT_INTERVAL: 1
EPOCHS: 20
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: null
  START_EPOCH: null
