DATA:
  BATCH_SIZE: 64
  AUGMENTATION: True
  SHUFFLE: True
OPTIMIZER:
  NAME: Adam
  PARAMS:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.e-08
SCHEDULER:
  USE: True
  NAME: StepLR
  PARAMS:
    step_size: 10
    gamma: 0.1
CRITERION:
  CUSTOM: False
  NAME: MSELoss
  PARAMS: null
DEVICE: "0,1,2"
DISTRIBUTED: True
LOG_DIR: "./logs"
LOG_INTERVAl: 1
VAL_INTERVAL: 2
CKPT_DIR: "./ckpts"
EPOCHS: 20

