DATA:
  ROOT_DIR: null
  BATCH_SIZE: 10
  AUGMENTATION:
    USE: True
    PARAMS: null
  TARGET_SCALE_FACTOR: 1.0 
OPTIMIZER:
  NAME: Adam
  LR: 0.0003
  PARAMS: #null
    betas: [0.9, 0.999]
    eps: 1.e-08
SCHEDULER:
  USE: True
  NAME: StepLR
  PARAMS:
    step_size: 10
    gamma: 0.1
CRITERION:
  CUSTOM: True
  NAME: L1Loss
  PARAMS: null
GRAD_CLIP: 
  USE: True
  VALUE: 1.0
DEVICE: "0"
DISTRIBUTED:
  USE: False
  WORLD_SIZE: 1
  RANK: 0
  BACKEND: nccl
  MASTER_ADDR: localhost
  MASTER_PORT: "12355"
LOG_DIR: "./logs"
LOG_ITERATIONS_INTERVAL: 1000
VALIDATE_INTERVAL: 2
VALIDATE_ON: loss
CKPT_DIR: "./ckpts"
CKPT_INTERVAL: 1
EPOCHS: 20
RESUME_TRAINING:
  CONSOLIDATED_CKPT: null
  EPOCHS: null
  START_EPOCH: null
