name: Code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8']
           
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pytest
        pip install pytest-cov codecov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build
        
    - name: Build package
      run: python -m build

    - name: Tests
      run: pytest --cov-report xml --cov='./ezflow/' --cov-config=.coveragerc

    - name: Code Coverage Report
      uses: codecov/codecov-action@v1
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        file: coverage.xml
        env_vars: OS,PYTHON